[project]
name = "racanus"
version = "2025.1.0"
description = "A chat website for Racan."

requires-python = ">=3.13"

dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.8",
    "sqlalchemy>=2.0.43",
    "pydantic-settings>=2.11.0",
]

[dependency-groups]
dev = [
    "taskipy>=1.14.1",
    "ruff>=0.13.0",
    "ty>=0.0.1a20",
]

[tool.taskipy.tasks]
lint = {cmd = "ruff check -e && ty check", help = "Lint, Format & Type Check the project."}
